language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - build-tools-28.0.3
  - android-26
before_install:
- chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: CLrWpdll/c+jYmkwjYBK3NrT67wfgRtqNiubZKFaxaW08uLDo0A962dTePVxFdb/yS5k1HgTFrJw6PdUDXw3qsV/R8UfgBqEmhhOgWCICJV1cy/8EX8b9Uq4liWzYNvJcwy8/8o0IJCOxnQ8q+CsiY6RvAbgQyhoQdg1ZbzTpnMd3pODW+2YJxT+p5jbiOA+ds3GkDGowJQ0FU0BnlyTx/tOlUplUdCCaHcS9J9YNlCzLnH18IZPOWyreFaCHO8wG2WGvRhRBwfU8BY6d45sVc8r0Vl2+k3YE+lWoJrB87zCM8JOGnyDS9lNjJvoutF9/1e7fKFoSyLF2/9Y7hfCn1I+SZ83Hms/oytLIYYrGZvN2M97/sxQ+SQHFfDMyC29r2SJa0TYAoP+plep3mYPDrfR90w+LUgoN+YR9XN9XsA+OT8pa4hWPTvpvGnQcnMWnkQbGMkhoBhVb3dwOfXoutDbR0wyXKI/WjDnWPJGUaHQvPQT4ckz5ztyOJ1hWr4Fu9wDxD1sRDZmBLwgggFMosd/t83thykZlb/hCQd9qeYeF89hGgYIiYuK/C3LybvImEqhooO5ilozRke9KBcimPskClFOA4AqwXYaMqN3uoKel1EH4fy4EQ6zPHNOtbFum5KZe+V+ViAQNzVZ17TyIJBGjerPboE7QH4P9ZzuVCE=
  file: Controlcenter/build/outputs/apk/release/Controlcenter-release-unsigned.apk
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true
